# name: Discord notification
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  notify-discord-server:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notifier
        # You may pin to the exact commit or the version.
        # uses: fateyan/action-discord-notifier@2d543d3e7e2c63546420b10f2652cb61e24578fc
        uses: fateyan/action-discord-notifier@v1.2.0
        with:
          # A full discord webhook url
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Message title
          message-title: New Commit